name: 'Banco Web - CI'

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Iniciar o servidor de mocks
        run: npm run mock-server &

      - name: Iniciar o servidor de aplicacao
        run: npm run server &

      - name: Executar os testes
        run: npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/reports"

      - name: Salvar o relatório dos testes
        uses: actions/upload-artifact@v4
        if: always() # Salva o artefato mesmo se os testes falharem
        with:
          name: relatorio-cypress
          path: cypress/reports/mochawesome.json
